# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 99ae2afa2ed77a3eaafa68a03ecb08e880ddaee397f95b38d6080e5c15d2d7d7eb7b99b58e1b3755574f6badfa6fe22df61acab0a3167a90c7421a7af2fdbe5b

test:
  secret_key_base: 70fea773b068b3fe2a48bb9588d148e8aedc9af7a7d66bf50d98196a70ccc352fc06e9745cfba460a54a461c7f5834bfafbe3ac5a06f2ed327a6778a7d5ed9ea

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
